# Generated by Django 5.2.11 on 2026-04-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '🔧 Admin'), ('principal', '👑 Principal'), ('teacher', '👩\u200d🏫 Teacher'), ('staff', '🧑\u200d💼 Non-Teaching Staff'), ('student', '👨\u200d🎓 Student')], default='student', max_length=20),
        ),
    ]
