# Generated by Django 5.2.11 on 2026-02-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('academic', '📚 Academic'), ('exam', '📝 Examination'), ('event', '🎉 Event'), ('holiday', '🏖️ Holiday'), ('urgent', '⚠️ Urgent'), ('general', '📢 General')], default='general', max_length=20),
        ),
    ]
