# Generated by Django 5.2.11 on 2026-02-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_to_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_to_students',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_to_teachers',
            field=models.BooleanField(default=False),
        ),
    ]
