# Generated by Django 5.2.11 on 2026-04-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_send_to_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
