# Generated by Django 5.2.11 on 2026-04-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_published_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='readstatus',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
