# Generated by Django 5.2.11 on 2026-04-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_options_readstatus_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readstatus',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
