# Generated by Django 5.2.11 on 2026-04-13 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_options_readstatus_reminder_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reminder_type', models.CharField(choices=[('meeting', 'Meeting'), ('assignment', 'Assignment'), ('exam', 'Exam'), ('event', 'Event'), ('deadline', 'Deadline'), ('general', 'General')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('scheduled_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('send_to_all_teachers', models.BooleanField(default=False)),
                ('send_to_all_students', models.BooleanField(default=False)),
                ('send_to_all_nonteaching', models.BooleanField(default=False)),
                ('send_to_principal', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='reminders/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='ReminderRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.reminder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reminder', 'user')},
            },
        ),
        migrations.AddField(
            model_name='reminder',
            name='recipients',
            field=models.ManyToManyField(related_name='received_reminders', through='notifications.ReminderRecipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('principal', 'Principal'), ('teacher', 'Teacher'), ('nonteaching', 'Non-Teaching Staff'), ('admin', 'Admin'), ('student', 'Student')], default='teacher', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('completion_step', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
