# Generated by Django 5.2.11 on 2026-04-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_readstatus_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='readstatus',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readstatus',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
