# Generated by Django 5.2.11 on 2026-04-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_readstatus_is_pinned_readstatus_pinned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload PDF, Image, or Document (Max: 10MB)', null=True, upload_to='notification_attachments/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='notification',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='attachment_size',
            field=models.IntegerField(default=0),
        ),
    ]
